webdrivers:
  chrome:
<<<<<<< HEAD
    path: 'C:\Users\pfifka\Downloads\chromedriver.exe'
=======
    path: 'C:\Users\tiash\Downloads\chromedriver.exe'
>>>>>>> ef7645d09ba875516841f952ec271cfda0e6493e
  firefox:
    path: 'firefox path'
  edge:
    path: 'edge path'
  safari:
    path: 'safari path'

applications:
  inventiweb:
    environments:
      PROD: "https://www.inventi.cz"
      TEST: "https://www.inventi.cz"
      DEV: "https://www.inventi.cz"
  dhl.smartops.user_management:
      environments:
        PROD: "https://um-dsc-smartops-fat.ocp1.dhl.com/um/#/"
        QA: "https://smartops-qa.dhl.com/um/#/"
  dhl.smartplan.smartplan:
      environments:
        DEV: ""
        FAT: "https://czcholstc001350.prg-dc.dhl.com:8443/login/user"
<<<<<<< HEAD
=======
  ness:
    environments:
      PROD: "https://www.ness.com/"
>>>>>>> ef7645d09ba875516841f952ec271cfda0e6493e

timeouts:
  VERY_SHORT: 1
  SHORT: 5
  MEDIUM: 20
  LONG: 60
  VERY_LONG: 300